# Pull gems from RubyGems
source 'https://rubygems.org'

gem 'sass', '~> 3.4.15'
gem 'compass', '~> 1.0.1'
gem 'singularitygs', '~> 1.3'
gem "singularity-extras", "~> 1.0.0.alpha.3"
gem 'breakpoint', '~> 2.5.x'
gem 'toolkit', '~> 2.6'
gem 'terminal-notifier'
gem 'compass-normalize', '~>1.4.3'

# Now that you're using Bundler, you need to run `bundle exec compass watch` instead of simply `compass watch`.
